config/routes.rb
AveventApp::Application.routes.draw do

  resources :photos

  resources :rsvps, :only => [:new, :create, :destroy]

  resources :events
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts
  
  match '/signin',     :to => 'sessions#new'
  match '/signout',    :to => 'sessions#destroy'
  match '/signup',     :to => 'users#new'
  match '/staff',      :to => 'sessions#staff'
  match '/about',      :to => 'pages#about'
  match '/faq',        :to => 'pages#faq'
  match '/social',     :to => 'pages#social'
  match '/personal',   :to => 'pages#personal'
  match '/fit',        :to => 'pages#fit'
  match '/financial',  :to => 'pages#financial'
  match '/career',     :to => 'pages#career'
  match '/community',  :to => 'pages#community'
  match '/possibility',     :to => 'pages#possibility'
  match '/pastevent',  :to => 'pages#past'
  
  root :to => 'pages#home'

end

app/models/event.rb
# == Schema Information
# Schema version: 20110528161010
#
# Table name: events
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  peak       :string(255)
#  start_time :datetime
#  end_time   :datetime
#  created_at :datetime
#  updated_at :datetime
#

class Event < ActiveRecord::Base
  has_many :rsvps
  has_many :users, :through => :rsvps
  has_many :photos
	has_many :microposts
  attr_accessible :name, :peak, :start_time, :end_time, :location, :info, :max_number, :image
  mount_uploader :image, ImageUploader
  scope :for_today, where(:start_time => Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
  scope :for_tomorrow, where(:start_time => Time.zone.now.tomorrow.beginning_of_day..Time.zone.now.tomorrow.end_of_day)
  scope :for_this_week, where(:start_time => Time.zone.now.beginning_of_week..Time.zone.now.end_of_week)
  scope :for_this_month, where(:start_time => Time.zone.now.beginning_of_month..Time.zone.now.end_of_month)
  scope :from_two_days_later, where("start_time > ?", Time.zone.now.midnight + 2.day)
  scope :from_this_week_later, where("start_time > ?", Time.zone.now.end_of_week)
  scope :is_active, where("start_time > ?", Time.zone.now.midnight)
  scope :is_past, where("start_time < ?", Time.zone.now.midnight)
  scope :peakcat, lambda {|peak| where(:peak => peak) }
  
  def vacancy?
    max_number > rsvps.count
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate, :only => [:index, :new, :create, :edit, :update, :destroy]
  before_filter :admin_user,   :only => [:index, :new, :create, :edit, :update, :destroy]
  # GET /events
  # GET /events.xml
  def index
    @events = Event.all

    #respond_to do |format|
    #  format.html  index.html.erb
    # format.xml  { render :xml => @events }
    #end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])
    @title = @event.name
    @rsvp = @event.rsvps
    @photo = @event.photos
    @existingpost = @event.microposts
    @micropost = Micropost.new(:event_id => @event) if signed_in?
    session[:return_to] = request.fullpath
	#@allname = User.find(@rsvp.user_id)
	
    #respond_to do |format|
    #  format.html  show.html.erb
    #  format.xml  { render :xml => @event }
    #end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create

    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @event, :html => {:multipart => true} do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
		<%= f.label :image %><br />
    <%= f.file_field :image %>
	</div>
  <div class="field">
    <%= f.label :peak %><br />
    <%= f.select :peak, options_for_select([ "Personal", "Fit", "Financial", "Social", "Career", "Community", "Possibility" ], @event.peak)%>
  </div>
	<div class="field">
		<%= f.label :location %><br />
		<%= f.text_field :location %>
	</div>
	<div class="field">
		<%= f.label :max_number %><br />
		<%#= f.text_field :max_number %>
		<%= f.select :max_number, (1..500) %>
	<div class="field">
		<%= f.label :info %><br />
		<%= f.text_area :info, :size => "10*8" %>
	</div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.datetime_select :end_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_month.html.erb
<div class="eventheader">
  <h2>Event List</h2>
</div>
<div class="mainCol">
  <div class="dateheader">
    <h3>Today</h3>
  </div>
</div>
<div class="eventRow">
</div>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Peak</th>
    <th>Start time</th>
    <th>End time</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
    <td><%= event.peak %></td>
    <td><%= event.start_time %></td>
    <td><%= event.end_time %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>

<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div class="leftCol">
  <%= image_tag @event.image_url(:eventthumb), :alt => @event.name, :class => "eventLogo" %>
  <div class="eventPeopleCount">
    <%= @event.rsvps.count %> Attending
  </div>
  <% if @rsvp.any? %>
  <ul>
    <% @rsvp.each do |rsvp| %>
      <li><%= User.find(rsvp.user_id).name %></li>
	  <% end %>
  </ul>
  <% end %>
</div>
<div class="rightContainer">
  <div class="headerArea">
    <div class="eventSideBtn">
      <% if signed_in? && current_user.admin? %>
        <%= link_to 'Edit', edit_event_path(@event) %>
        Message Guests
      <% end %>
    </div>
    <div class="profileHeader">
      <h1><%= @event.name %></h1>
      <div>
          <% if signed_in? %>
            <% if current_user.attending?(@event) %>
							<% ticket = current_user.rsvps.find_by_event_id(@event) %>
              <%= form_for ticket, :html => {:method => :delete } do |f| %>
								<div class="field">
									<%= f.label :notes %>
							    <%= ticket.notes %>
								</div>
                <div class="actions"><%= f.submit "Not Attend" %></div>
              <% end %>
            <% else %>
							<% if @event.vacancy? %>
	              <%= form_for current_user.rsvps.build(:event_id => @event.id) do |f| %>
		              <div><%= f.hidden_field :event_id %></div>
									<div>
										<%= f.label :notes %>
										<%= f.text_field :notes %>
									</div>
		              <div class="actions"><%= f.submit "Attend" %></div>
								<% end %>
							<% else %>
								<div>
									There is no more vacancy for this event.
								</div>
							<% end %>
            <% end %>
          <% else %>
            <%= button_to 'RSVP', signin_path %>
          <% end %>
      </div>
    </div>
  </div>
  <div class="eventInfo">
    <table class="eventInfoTable">
      <tbody>
        <tr>
          <th class="label">Time:</th>
          <td class="data"><%= @event.start_time.strftime("%A, %b %d at %I:%M%p") %> - <%= @event.end_time.strftime("%I:%M%p") %></td>
        </tr>
        <tr>
          <th class="label">Location:</th>
          <td class="data"><%= @event.location %></td>
        </tr>
        <tr>
          <th class="label">Event Info:</th>
          <td class="data"><%= @event.info %></td>
        </tr>
				<% if signed_in? && current_user.admin? %>
				<tr>
					<th class="label">Max Number</th>
					<td class="data"><%= @event.max_number %></td>
				</tr>
				<% end %>
      </tbody>
    </table>
		<div id="eventPhotos">
			<h4>Event Photo</h4>
			<ul>
			<% for photo in @photo %>
				<li><%= link_to image_tag(photo.image_url(:thumb)), photo.image_url if photo.image? %></li>
			<% end %>
			</ul>
		</div>
		<% if signed_in? %>
			<div>
				<%= link_to "Upload photo", new_photo_path(:event_id => @event) %>
			</div>
		<% end %>
		<div id="eventWalls">
			<h4>Wall</h4>
			<% for post in @existingpost %>
				<p>
					<%= User.find(post.user_id).name %> says:
					<%= post.content %>
				</p>
			<% end %>
			<% if signed_in? %>
				<%= form_for @micropost do |f| %>
	        <div><%= f.hidden_field :event_id, :value => @event.id %></div>
					<div>
						<%= f.label :content %>
						<%= f.text_field :content %>
					</div>
	        <div class="actions"><%= f.submit "Post" %></div>
				<% end %>
			<% end %>
		</div>
  </div>
</div>
<div style="clear:both"></div>