config/routes.rb
AveventApp::Application.routes.draw do

  resources :photos

  resources :rsvps, :only => [:new, :create, :destroy]

  resources :events
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts
  
  match '/signin',     :to => 'sessions#new'
  match '/signout',    :to => 'sessions#destroy'
  match '/signup',     :to => 'users#new'
  match '/staff',      :to => 'sessions#staff'
  match '/about',      :to => 'pages#about'
  match '/faq',        :to => 'pages#faq'
  match '/social',     :to => 'pages#social'
  match '/personal',   :to => 'pages#personal'
  match '/fit',        :to => 'pages#fit'
  match '/financial',  :to => 'pages#financial'
  match '/career',     :to => 'pages#career'
  match '/community',  :to => 'pages#community'
  match '/possibility',     :to => 'pages#possibility'
  match '/pastevent',  :to => 'pages#past'
  
  root :to => 'pages#home'

end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  attr_accessible :event_id, :notes
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  #before_filter :authenticate
  # GET /rsvps
  # GET /rsvps.xml
  def index
    @rsvps = Rsvp.all
  end

  # GET /rsvps/1
  # GET /rsvps/1.xml
  def show
    @rsvp = Rsvp.find(params[:id])

  end

  # GET /rsvps/new
  # GET /rsvps/new.xml
  def new
    @rsvp = Rsvp.new
  end

  # GET /rsvps/1/edit
  def edit
    @rsvp = Rsvp.find(params[:id])
  end

  # POST /rsvps
  # POST /rsvps.xml
  def create
    @event = Event.find(params[:rsvp][:event_id])
    note = params[:rsvp][:notes]
    if @event.vacancy?
      current_user.attend!(@event, note)
      redirect_to event_path(@event), :notice => "RSVP Saved"
    else
      redirect_to event_path(@event), :alert => "Sorry, No more vacancy for this event"
    end
    #@rsvp = Rsvp.new(params[:rsvp])
  end

  # PUT /rsvps/1
  # PUT /rsvps/1.xml
  def update
    @rsvp = Rsvp.find(params[:id])
  end

  # DELETE /rsvps/1
  # DELETE /rsvps/1.xml
  def destroy
    @event = Rsvp.find(params[:id]).event_id
    current_user.unattend!(@event)
    redirect_to event_path(@event), :notice => "RSVP Saved"
  end
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/views/rsvps/_form.html.erb
<%= form_for(@rsvp) do |f| %>
  <% if @rsvp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rsvp.errors.count, "error") %> prohibited this rsvp from being saved:</h2>

      <ul>
      <% @rsvp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br />
    <%= f.text_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rsvps/edit.html.erb
<h1>Editing rsvp</h1>

<%= render 'form' %>

<%= link_to 'Show', @rsvp %> |
<%= link_to 'Back', rsvps_path %>

app/views/rsvps/index.html.erb
<h1>Listing rsvps</h1>

<table>
  <tr>
    <th>User</th>
    <th>Event</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rsvps.each do |rsvp| %>
  <tr>
    <td><%= rsvp.user_id %></td>
    <td><%= rsvp.event_id %></td>
    <td><%= rsvp.notes %></td>
    <td><%= link_to 'Show', rsvp %></td>
    <td><%= link_to 'Edit', edit_rsvp_path(rsvp) %></td>
    <td><%= link_to 'Destroy', rsvp, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rsvp', new_rsvp_path %>

app/views/rsvps/new.html.erb
<h1>New rsvp</h1>

<%= render 'form' %>

<%= link_to 'Back', rsvps_path %>

app/views/rsvps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @rsvp.user_id %>
</p>

<p>
  <b>Event:</b>
  <%= @rsvp.event_id %>
</p>

<p>
  <b>Notes:</b>
  <%= @rsvp.notes %>
</p>


<%= link_to 'Edit', edit_rsvp_path(@rsvp) %> |
<%= link_to 'Back', rsvps_path %>