config/routes.rb
AveventApp::Application.routes.draw do

  resources :photos

  resources :rsvps, :only => [:new, :create, :destroy]

  resources :events
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts
  
  match '/signin',     :to => 'sessions#new'
  match '/signout',    :to => 'sessions#destroy'
  match '/signup',     :to => 'users#new'
  match '/staff',      :to => 'sessions#staff'
  match '/about',      :to => 'pages#about'
  match '/faq',        :to => 'pages#faq'
  match '/social',     :to => 'pages#social'
  match '/personal',   :to => 'pages#personal'
  match '/fit',        :to => 'pages#fit'
  match '/financial',  :to => 'pages#financial'
  match '/career',     :to => 'pages#career'
  match '/community',  :to => 'pages#community'
  match '/possibility',     :to => 'pages#possibility'
  match '/pastevent',  :to => 'pages#past'
  
  root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer>

</footer>

app/views/layouts/_header.html.erb
<header>
  <%#= link_to logo, root_path %>
  <nav>
    <ul id="jsddm">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About Basecamp", about_path %></li>
	  <% if signed_in? %>
        <% if current_user.admin? %>
		  <li><%= link_to "Event", events_path %></li>
		<% end %>
      <% end %>
      <li><a href="#">The 7 Peaks</a>
        <ul>
          <li><%= link_to "Personal", personal_path %></li>
          <li><%= link_to "Fit", fit_path %></li>
          <li><%= link_to "Financial", financial_path %></li>
          <li><%= link_to "Social", social_path %></li>
          <li><%= link_to "Career", career_path %></li>
          <li><%= link_to "Community", community_path %></li>
          <li><%= link_to "Possibility", possibility_path %></li>
        </ul>
      </li>
    </ul>
  </nav>
  <nav class="right">
    <ul>
      <% if signed_in? %>
      <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "Staff Entrance", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %></title>
    <%= csrf_meta_tag %>
	<%= render 'layouts/stylesheets' %>
	<%= javascript_include_tag :defaults %>
  <%= javascript_include_tag 'dropdown' %>
  </head>
  <body>
	<div class="container">
		<%= render 'layouts/header' %>
		<section>
			<% flash.each do |key, value| %>
				<div class="flash <%= key %>"><%= value %></div>
			<% end %>
			<%= yield %>
		</section>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
  </body>
</html>